import { Scheme } from './types'

export const SCHEMES: Scheme[] = [
  {
    id: 'scheme-001',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    department: 'Ministry of Skill Development & Entrepreneurship',
    description: 'A flagship scheme to impart industry-relevant skills to Indian youth and help them secure better employment.',
    eligibility: ['Age 15-45', 'Indian Citizen', 'No formal educational qualification required'],
    benefits: ['Free skill training', 'Industry certification', 'Job placement assistance', '₹8000 financial assistance'],
    financialAssistance: '₹8000 per training course',
    requiredDocuments: ['Aadhar Card', 'PAN Card', 'Bank Account Details', 'Educational Certificate'],
    applicationDeadline: '31 December 2025',
    targetAudience: ['Youth', 'Job Seekers', 'Unemployed'],
    category: 'Skill Development',
    applicationUrl: 'https://pmkvy.gov.in',
    contactPhone: '1800-123-4567',
  },
  {
    id: 'scheme-002',
    name: 'Pradhan Mantri Awas Yojana (Housing)',
    department: 'Ministry of Housing and Urban Affairs',
    description: 'Affordable housing scheme for economically weaker sections to own a home.',
    eligibility: ['Annual income ≤ ₹6 lakh', 'No existing house', 'Family size ≤ 5 members', 'Age 21-55 years'],
    benefits: ['Subsidy up to ₹2.67 lakh', 'Home loan assistance', 'Lower interest rates'],
    financialAssistance: '₹2.67 lakh interest subsidy',
    requiredDocuments: ['Aadhar Card', 'Income Certificate', 'Residence Proof', 'Bank Account Details', 'Property Documents'],
    applicationDeadline: '31 December 2025',
    targetAudience: ['Low Income Families', 'First Time Home Buyers'],
    category: 'Housing',
    applicationUrl: 'https://pmay.gov.in',
    contactPhone: '1800-200-4200',
  },
  {
    id: 'scheme-003',
    name: 'National Scholarship Portal',
    department: 'Ministry of Education',
    description: 'Various scholarships for meritorious students from economically weaker backgrounds.',
    eligibility: ['School/College student', 'Annual family income ≤ ₹8 lakh', 'Merit-based selection'],
    benefits: ['₹6000-₹50000 annual scholarship', 'Merit recognition', 'Career guidance'],
    financialAssistance: '₹6000 to ₹50000 per annum',
    requiredDocuments: ['12th Pass Certificate', 'Income Certificate', 'Bank Account Details', 'Aadhar Card', 'Educational Transcripts'],
    applicationDeadline: '15 September 2025',
    targetAudience: ['Students', 'Merit Scholars'],
    category: 'Education',
    applicationUrl: 'https://scholarships.gov.in',
    contactPhone: '1800-180-1111',
  },
  {
    id: 'scheme-004',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    department: 'Ministry of Finance',
    description: 'Financial inclusion scheme to provide banking services to all citizens.',
    eligibility: ['All Indian citizens above 10 years', 'No banking account required'],
    benefits: ['Zero-balance bank account', 'Life insurance coverage up to ₹1 lakh', 'Accident insurance ₹2 lakh', 'Debit card'],
    financialAssistance: 'Insurance coverage up to ₹3 lakh',
    requiredDocuments: ['Aadhar Card or Voter ID', 'Address Proof'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Unbanked Citizens', 'All Indians'],
    category: 'Financial Inclusion',
    applicationUrl: 'https://pmjdy.gov.in',
    contactPhone: '1800-425-1969',
  },
  {
    id: 'scheme-005',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    department: 'Ministry of Agriculture',
    description: 'Crop insurance scheme for farmers to protect against crop loss.',
    eligibility: ['Farmer with agricultural land', 'Crops notified under scheme', 'No age restriction'],
    benefits: ['Crop loss insurance', 'Uniform premium rates', 'Claim settlement'],
    financialAssistance: 'Insurance coverage based on crop value',
    requiredDocuments: ['Aadhar Card', 'Land Records', 'Crop Details', 'Bank Account Details'],
    applicationDeadline: '31 July (varies by state)',
    targetAudience: ['Farmers', 'Landowners'],
    category: 'Agriculture',
    applicationUrl: 'https://pmfby.gov.in',
    contactPhone: '1800-180-1551',
  },
  {
    id: 'scheme-006',
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    department: 'Ministry of Finance',
    description: 'Micro loans for small businesses and self-employed individuals.',
    eligibility: ['Individual entrepreneur', 'Non-farm micro-business', 'Age 18+ years', 'No prior loan history'],
    benefits: ['Loans up to ₹10 lakh', 'No collateral required', 'Flexible repayment', 'Government-backed loans'],
    financialAssistance: 'Loans up to ₹10 lakh',
    requiredDocuments: ['Aadhar Card', 'Business Plan', 'Proof of Residence', 'Photograph', 'Bank Account Details'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Entrepreneurs', 'Self-Employed', 'Small Business'],
    category: 'Business & Employment',
    applicationUrl: 'https://www.mudrayojana.gov.in',
    contactPhone: '1800-180-2290',
  },
  {
    id: 'scheme-007',
    name: 'Atmanirbhar Bharat Rojgar Yojana',
    department: 'Ministry of Labour',
    description: 'Employment incentive scheme for new workers during COVID-19 recovery.',
    eligibility: ['New employee on payroll from August 2020', 'Monthly salary ≤ ₹15000', 'Age 18-65 years'],
    benefits: ['Employer contribution to EPF', 'Employee contribution to EPF for 2 years', 'Additional incentives'],
    financialAssistance: 'Employer/Employee EPF contribution subsidy',
    requiredDocuments: ['Employment Letter', 'Aadhar Card', 'Bank Account Details', 'EPF Details'],
    applicationDeadline: '30 June 2024',
    targetAudience: ['New Employees', 'Workers', 'First Time Job Holders'],
    category: 'Employment',
    applicationUrl: 'https://labour.gov.in',
    contactPhone: '1800-220-4141',
  },
  {
    id: 'scheme-008',
    name: 'Sukanya Samriddhi Yojana',
    department: 'Ministry of Finance',
    description: 'Savings scheme for girls to secure their future education and marriage.',
    eligibility: ['Girl child below 10 years', 'Indian citizen'],
    benefits: ['7.8% interest rate (updated annually)', 'Tax deduction up to ₹1.5 lakh', 'Partial withdrawals allowed'],
    financialAssistance: 'Interest earned at market rates',
    requiredDocuments: ['Birth Certificate', 'Aadhar Card of Girl Child', 'Parent/Guardian ID', 'Address Proof'],
    applicationDeadline: 'Can open any time',
    targetAudience: ['Girl Child', 'Parents', 'Guardians'],
    category: 'Savings & Financial Security',
    applicationUrl: 'https://ssy.nsiindia.gov.in',
    contactPhone: '1800-300-2000',
  },
  {
    id: 'scheme-009',
    name: 'Ayushman Bharat - PM-JAY',
    department: 'Ministry of Health',
    description: 'World\'s largest health insurance scheme providing free treatment.',
    eligibility: ['Family income below ₹3 lakh annually', 'BPL families', 'SECC cardholders'],
    benefits: ['Cashless hospitalization up to ₹5 lakh annually', 'All secondary and tertiary treatments', 'Ambulance service'],
    financialAssistance: 'Free hospitalization up to ₹5 lakh per year',
    requiredDocuments: ['Aadhar Card', 'Ration Card', 'Income Certificate', 'Address Proof'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Low Income Families', 'BPL', 'Uninsured Poor'],
    category: 'Healthcare',
    applicationUrl: 'https://pmjay.gov.in',
    contactPhone: '1800-300-3000',
  },
  {
    id: 'scheme-010',
    name: 'Senior Citizen Pension Scheme',
    department: 'Ministry of Social Justice',
    description: 'Monthly pension for senior citizens aged 60 and above with no income.',
    eligibility: ['Age 60 years or above', 'Annual income ≤ ₹1.25 lakh (couples ₹2.5 lakh)', 'Indian citizen', 'Not receiving any other pension'],
    benefits: ['₹500-1200 monthly pension', 'Medical assistance', 'Subsidized utilities'],
    financialAssistance: '₹500-1200 per month',
    requiredDocuments: ['Age Proof', 'Income Certificate', 'Bank Account Details', 'Aadhar Card'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Senior Citizens 60+', 'Retired Poor'],
    category: 'Social Security',
    applicationUrl: 'https://socialjustice.gov.in',
    contactPhone: '1800-180-2200',
  },
  {
    id: 'scheme-011',
    name: 'Beti Bachao Beti Padhao',
    department: 'Ministry of Women & Child Development',
    description: 'Multi-dimensional scheme for girl child welfare, education, and protection.',
    eligibility: ['Families with girl children', 'All income groups'],
    benefits: ['Educational incentives', 'Healthcare support', 'Legal aid', 'Skill development'],
    financialAssistance: 'Varies based on state programs',
    requiredDocuments: ['Birth Certificate of Girl Child', 'Parents ID Proof', 'Address Proof', 'Aadhar Card'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Girl Child', 'Women', 'Families'],
    category: 'Women & Child Welfare',
    applicationUrl: 'https://wcd.nic.in',
    contactPhone: '1800-180-2323',
  },
  {
    id: 'scheme-012',
    name: 'National Social Assistance Programme (NSAP)',
    department: 'Ministry of Social Justice',
    description: 'Social assistance for vulnerable groups including elderly, widows, and disabled.',
    eligibility: ['Elderly 60+', 'Widows', 'Disabled persons', 'Low income'],
    benefits: ['Monthly assistance ₹200-500', 'Healthcare support', 'Disability benefits'],
    financialAssistance: '₹200-500 per month',
    requiredDocuments: ['Age/Disability Certificate', 'Income Proof', 'Bank Account', 'Aadhar Card'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Elderly', 'Widows', 'Disabled'],
    category: 'Social Security',
    applicationUrl: 'https://nsap.nic.in',
    contactPhone: '1800-180-2121',
  },
  {
    id: 'scheme-013',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana',
    department: 'Ministry of Finance',
    description: 'Low-cost life insurance scheme providing coverage for death due to any reason.',
    eligibility: ['Age 18-50 years', 'Active bank account holder', 'Indian citizen', 'Annual income ≤ ₹1.5 lakh'],
    benefits: ['Death coverage ₹2 lakh', 'Premium ₹436 per year', 'No medical exam required'],
    financialAssistance: 'Life cover ₹2 lakh',
    requiredDocuments: ['Aadhar Card', 'Bank Account Details', 'Income Certificate', 'Medical Declaration'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Young Adults', 'Low Income', 'Self-Employed'],
    category: 'Insurance',
    applicationUrl: 'https://pmjjby.gov.in',
    contactPhone: '1800-180-1177',
  },
  {
    id: 'scheme-014',
    name: 'Stand Up India Scheme',
    department: 'Ministry of Finance',
    description: 'Financing scheme for SC/ST and women entrepreneurs to start enterprises.',
    eligibility: ['SC/ST/Women entrepreneur', 'Age 18-65 years', 'First-time entrepreneur', 'Business idea/plan'],
    benefits: ['Bank loan ₹10-50 lakh', 'Lower interest rates', 'Mentoring support', 'Incubation assistance'],
    financialAssistance: 'Bank loan up to ₹50 lakh',
    requiredDocuments: ['Business Plan', 'Aadhar Card', 'Caste Certificate (if applicable)', 'Bank Account Details', 'Collateral Documents'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['SC/ST', 'Women Entrepreneurs', 'First-time Business'],
    category: 'Entrepreneurship',
    applicationUrl: 'https://standupmitra.in',
    contactPhone: '1800-180-2323',
  },
  {
    id: 'scheme-015',
    name: 'Pradhan Mantri Maternity Benefit Scheme',
    department: 'Ministry of Women & Child Development',
    description: 'Cash assistance scheme for pregnant women during pregnancy and lactation.',
    eligibility: ['Pregnant women', 'First two live births', 'Registered for scheme', 'Age 19+ years'],
    benefits: ['₹6000 cash assistance', 'Free institutional delivery', 'Nutrition support'],
    financialAssistance: '₹6000 in installments',
    requiredDocuments: ['Medical Certificate', 'Age Proof', 'Pregnancy Documents', 'Bank Account Details', 'Aadhar Card'],
    applicationDeadline: 'During pregnancy',
    targetAudience: ['Pregnant Women', 'Lactating Mothers'],
    category: 'Maternal Health',
    applicationUrl: 'https://pmmb.nic.in',
    contactPhone: '1800-180-1800',
  },
  {
    id: 'scheme-016',
    name: 'Pradhan Mantri Shram Yogi Maan-Dhan Yojana (PM-SYM)',
    department: 'Ministry of Labour',
    description: 'Pension scheme for unorganized workers providing social security.',
    eligibility: ['Age 18-40 years', 'Monthly income ≤ ₹15000', 'Not covered under other schemes', 'Unorganized sector worker'],
    benefits: ['₹3000 monthly pension from age 60', 'Family pension benefits', 'Disability coverage'],
    financialAssistance: '₹3000 monthly pension after age 60',
    requiredDocuments: ['Aadhar Card', 'Bank Account Details', 'Mobile Number', 'Income Declaration', 'Occupation Proof'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Unorganized Workers', 'Informal Sector', 'Self-Employed'],
    category: 'Social Security',
    applicationUrl: 'https://maandhan.in',
    contactPhone: '1800-180-5174',
  },
  {
    id: 'scheme-017',
    name: 'Pradhan Mantri Garib Kalyan Yojana',
    department: 'Ministry of Finance',
    description: 'Social security and food security scheme for poor and marginalized.',
    eligibility: ['Below Poverty Line (BPL)', 'All family members registered'],
    benefits: ['Free grain rations', 'Cash transfers', 'Healthcare services', 'Insurance coverage'],
    financialAssistance: 'Free food grains and cash transfers',
    requiredDocuments: ['Ration Card', 'BPL Certificate', 'Aadhar Card', 'Bank Account Details'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['BPL Families', 'Poor & Marginalized'],
    category: 'Food & Social Security',
    applicationUrl: 'https://pgky.gov.in',
    contactPhone: '1800-180-1551',
  },
  {
    id: 'scheme-018',
    name: 'Startup India Scheme',
    department: 'Ministry of Commerce',
    description: 'End-to-end support for startups and entrepreneurs in India.',
    eligibility: ['Registered startup', 'Operating since <7 years', 'Innovation-based business', 'Annual turnover <₹25 crore'],
    benefits: ['Tax benefits', 'Simplified compliance', 'Patent rebate 80%', 'Funding assistance'],
    financialAssistance: 'Various grants and tax benefits',
    requiredDocuments: ['Business Registration', 'Founder ID', 'Business Plan', 'Financial Statements', 'Innovation Details'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Entrepreneurs', 'Innovators', 'Tech Startups'],
    category: 'Entrepreneurship',
    applicationUrl: 'https://www.startupindia.gov.in',
    contactPhone: '1800-180-1888',
  },
  {
    id: 'scheme-019',
    name: 'National Apprenticeship Promotion Scheme (NAPS)',
    department: 'Ministry of Skill Development',
    description: 'Apprenticeship training scheme for youth in various trades.',
    eligibility: ['Age 15-25 years', '8th pass or above', 'Physical fitness'],
    benefits: ['Stipend during training', 'Apprenticeship certificate', 'Job placement assistance', 'Skill certification'],
    financialAssistance: 'Stipend ₹4000-10000 per month',
    requiredDocuments: ['Educational Certificate', 'Age Proof', 'Aadhar Card', 'Medical Certificate', 'Address Proof'],
    applicationDeadline: 'Ongoing (varies by trade)',
    targetAudience: ['Youth', 'School Leavers', 'Job Seekers'],
    category: 'Skill Development',
    applicationUrl: 'https://www.apprenticeshipindia.gov.in',
    contactPhone: '1800-180-5174',
  },
  {
    id: 'scheme-020',
    name: 'Integrated Child Protection Scheme (ICPS)',
    department: 'Ministry of Women & Child Development',
    description: 'Comprehensive scheme for protection and welfare of vulnerable children.',
    eligibility: ['Children below 18 years', 'Vulnerable/in need of care and protection', 'Orphans, abandoned, exploited'],
    benefits: ['Shelter and care', 'Education support', 'Medical assistance', 'Rehabilitation services'],
    financialAssistance: 'Shelter, food, education, healthcare provided',
    requiredDocuments: ['Age Proof', 'Guardianship Documents', 'Medical Records', 'Educational Details'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['Children', 'Orphans', 'Vulnerable Youth'],
    category: 'Child Welfare',
    applicationUrl: 'https://icps.nic.in',
    contactPhone: '1800-180-1118',
  },
  {
    id: 'scheme-021',
    name: 'Pradhan Mantri Ujjwala Yojana',
    department: 'Ministry of Petroleum',
    description: 'Scheme to provide LPG connections to below poverty line households.',
    eligibility: ['BPL families', 'Women heads of household', 'No existing LPG connection'],
    benefits: ['Free LPG connection', 'First cylinder free', 'Subsidy on subsequent cylinders'],
    financialAssistance: 'Free connection + first cylinder + Rs 1600 subsidy',
    requiredDocuments: ['BPL Certificate', 'Ration Card', 'Address Proof', 'ID Proof'],
    applicationDeadline: 'Ongoing',
    targetAudience: ['BPL Families', 'Women', 'Low Income'],
    category: 'Energy & Utilities',
    applicationUrl: 'https://pmuy.gov.in',
    contactPhone: '1800-250-5000',
  },
]
