import { Scheme } from './types'

export const SCHEMES: Scheme[] = [
  {
    id: 'scheme-001',
    name: 'Pradhan Mantri Kaushal Vikas Yojana (PMKVY)',
    department: 'Ministry of Skill Development & Entrepreneurship',
    description: 'A flagship scheme to impart industry-relevant skills to Indian youth and help them secure better employment.',
    detailedInfo: 'PMKVY is a flagship scheme for skilling at scale at speed with quality. The scheme aims to provide industry-relevant skill training to youth to enhance their employability and help them secure better livelihoods.',
    eligibility: ['Age 15-45', 'Indian Citizen', 'No formal educational qualification required', 'Willing to undergo skill training'],
    benefits: ['Free skill training', 'Industry certification', 'Job placement assistance', '₹8000 financial assistance', 'Hostel facility for trainees'],
    financialAssistance: '₹8000 per training course',
    requiredDocuments: [
      { name: 'Aadhar Card', description: 'Original or copy', optional: false },
      { name: 'PAN Card', description: 'For income verification (if applicable)', optional: true },
      { name: 'Bank Account Details', description: 'For stipend transfer', optional: false },
      { name: 'Educational Certificate', description: '10th pass or equivalent', optional: false },
      { name: 'Passport Size Photograph', description: '2 photos (4x6 cm)', optional: false },
    ],
    applicationDeadline: '31 December 2025',
    applicationProcess: ['Visit PMKVY website', 'Register and complete profile', 'Choose training center and course', 'Attend interviews', 'Enroll in training program', 'Complete training and get certification'],
    targetAudience: ['Youth', 'Job Seekers', 'Unemployed', 'School Dropouts'],
    category: 'Skill Development',
    applicationUrl: 'https://pmkvy.gov.in',
    contactPhone: '1800-123-4567',
    faq: [
      { question: 'Is there any fee for PMKVY training?', answer: 'No, training is completely free for candidates.' },
      { question: 'What is the age limit for PMKVY?', answer: 'The age limit is 15-45 years.' },
      { question: 'Will I get a job after completing the training?', answer: 'Yes, 100% placement assistance is provided.' },
    ],
  },
  {
    id: 'scheme-002',
    name: 'Pradhan Mantri Awas Yojana (Housing)',
    department: 'Ministry of Housing and Urban Affairs',
    description: 'Affordable housing scheme for economically weaker sections to own a home.',
    detailedInfo: 'A comprehensive mission to achieve "Housing for All" by facilitating easy access to housing finance at affordable rates for all eligible beneficiaries irrespective of their income group.',
    eligibility: ['Annual income ≤ ₹6 lakh', 'No existing house in India', 'Family size ≤ 5 members', 'Age 21-55 years', 'Indian citizen'],
    benefits: ['Subsidy up to ₹2.67 lakh', 'Home loan assistance', 'Lower interest rates', 'Tax benefits', 'Flexible repayment period'],
    financialAssistance: '₹2.67 lakh interest subsidy',
    requiredDocuments: [
      { name: 'Aadhar Card', description: 'Photo ID proof', optional: false },
      { name: 'Income Certificate', description: 'From revenue authority', optional: false },
      { name: 'Residence Proof', description: 'Utility bill or rental agreement', optional: false },
      { name: 'Bank Account Details', description: 'For subsidy transfer', optional: false },
      { name: 'Property Documents', description: 'Land/property papers', optional: false },
      { name: 'Loan Sanction Letter', description: 'From bank/NBFC', optional: true },
    ],
    applicationDeadline: '31 December 2025',
    applicationProcess: ['Check eligibility', 'Submit application to housing authority', 'Get income verification', 'Bank approval for loan', 'Property registration', 'Subsidy disbursement'],
    targetAudience: ['Low Income Families', 'First Time Home Buyers', 'EWS category'],
    category: 'Housing',
    applicationUrl: 'https://pmay.gov.in',
    contactPhone: '1800-200-4200',
    faq: [
      { question: 'What is the maximum loan amount eligible?', answer: 'Up to ₹20 lakh for urban areas and ₹10 lakh for rural.' },
      { question: 'How much is the interest subsidy?', answer: 'Credit-linked subsidy of 3-4% on the home loan amount.' },
    ],
  },
  {
    id: 'scheme-003',
    name: 'National Scholarship Portal',
    department: 'Ministry of Education',
    description: 'Various scholarships for meritorious students from economically weaker backgrounds.',
    detailedInfo: 'The National Scholarship Portal (NSP) serves as a single-window online platform for students to apply for various scholarships from central and state governments.',
    eligibility: ['School/College student (Class 1 to PG)', 'Annual family income ≤ ₹8 lakh', 'Merit-based selection', 'Indian citizen'],
    benefits: ['₹6000-₹50000 annual scholarship', 'Merit recognition', 'Career guidance', 'Educational counseling'],
    financialAssistance: '₹6000 to ₹50000 per annum',
    requiredDocuments: [
      { name: '12th Pass Certificate', description: 'Educational qualification proof', optional: false },
      { name: 'Income Certificate', description: 'From government authority', optional: false },
      { name: 'Bank Account Details', description: 'For scholarship transfer', optional: false },
      { name: 'Aadhar Card', description: 'Unique identification', optional: false },
      { name: 'Mark Sheet', description: 'Previous year marks', optional: false },
      { name: 'Caste Certificate', description: 'If applicable (SC/ST/OBC)', optional: true },
    ],
    applicationDeadline: '15 September 2025',
    applicationProcess: ['Register on NSP portal', 'Fill scholarship application', 'Upload documents', 'Merit evaluation', 'Scholarship approval', 'Fund transfer to bank'],
    targetAudience: ['Students', 'Merit Scholars', 'Underprivileged Students'],
    category: 'Education & Scholarships',
    applicationUrl: 'https://scholarships.gov.in',
    contactPhone: '1800-180-1111',
    faq: [
      { question: 'When is the scholarship application window open?', answer: 'Usually from July to September each year.' },
      { question: 'How long does it take to receive scholarship?', answer: '2-3 months after approval.' },
    ],
  },
  {
    id: 'scheme-004',
    name: 'Pradhan Mantri Jan Dhan Yojana (PMJDY)',
    department: 'Ministry of Finance',
    description: 'Financial inclusion scheme to provide banking services to all citizens.',
    detailedInfo: 'A national mission to financial inclusion by providing access to financial services, including bank accounts, credit, insurance, and pensions.',
    eligibility: ['All Indian citizens above 10 years', 'No existing bank account required', 'Any income group'],
    benefits: ['Zero-balance bank account', 'Life insurance coverage up to ₹1 lakh', 'Accident insurance ₹2 lakh', 'Free debit card', 'RuPay card'],
    financialAssistance: 'Insurance coverage up to ₹3 lakh',
    requiredDocuments: [
      { name: 'Aadhar Card', description: 'Primary identification', optional: false },
      { name: 'Voter ID', description: 'Alternative ID', optional: true },
      { name: 'Address Proof', description: 'Utility bill or lease agreement', optional: false },
      { name: 'Photograph', description: '1 passport-sized photo', optional: true },
    ],
    applicationDeadline: 'Ongoing',
    applicationProcess: ['Visit nearest bank branch', 'Verify identity and address', 'Complete account opening form', 'Submit documents', 'Receive debit card and benefits'],
    targetAudience: ['Unbanked Citizens', 'All Indians', 'Low Income Groups'],
    category: 'Financial Inclusion',
    applicationUrl: 'https://pmjdy.gov.in',
    contactPhone: '1800-425-1969',
    faq: [
      { question: 'Is there any maintenance fee?', answer: 'No, it is a zero-balance account with no minimum balance required.' },
      { question: 'What is the insurance coverage?', answer: 'Life cover ₹1 lakh + Accident cover ₹2 lakh automatically.' },
    ],
  },
  {
    id: 'scheme-005',
    name: 'Pradhan Mantri Fasal Bima Yojana (PMFBY)',
    department: 'Ministry of Agriculture',
    description: 'Crop insurance scheme for farmers to protect against crop loss due to natural calamities.',
    detailedInfo: 'A comprehensive insurance scheme designed to provide insurance coverage and financial support to farmers against crop losses due to natural calamities, pests, and diseases.',
    eligibility: ['Farmer with agricultural land', 'Crops notified under scheme', 'No age restriction', 'Tenant farmer with lease document'],
    benefits: ['Crop loss insurance coverage', 'Uniform premium rates', 'Quick claim settlement', 'Coverage of all crops'],
    financialAssistance: 'Insurance coverage based on crop value (up to ₹2 lakh per hectare)',
    requiredDocuments: [
      { name: 'Aadhar Card', description: 'Farmer identification', optional: false },
      { name: 'Land Records', description: 'Khata/Girdawari papers', optional: false },
      { name: 'Crop Details', description: 'Crop name and sown area', optional: false },
      { name: 'Bank Account Details', description: 'For claim disbursement', optional: false },
      { name: 'Photographs', description: 'Photos of crops and land', optional: true },
    ],
    applicationDeadline: '31 July (varies by state)',
    applicationProcess: ['Register as farmer', 'Provide crop and land details', 'Pay insurance premium', 'Receive policy document', 'File claim after loss', 'Get claim amount'],
    targetAudience: ['Farmers', 'Landowners', 'Agricultural Workers'],
    category: 'Agriculture & Farming',
    applicationUrl: 'https://pmfby.gov.in',
    contactPhone: '1800-180-1551',
    faq: [
      { question: 'What is the insurance premium percentage?', answer: 'Farmer premium: 2% for cereals, 5% for pulses, 5% for oilseeds.' },
      { question: 'How long does claim settlement take?', answer: 'Usually 1-2 months from claim submission.' },
    ],
  },
  {
    id: 'scheme-006',
    name: 'Pradhan Mantri Mudra Yojana (PMMY)',
    department: 'Ministry of Finance',
    description: 'Micro loans for small businesses and self-employed individuals without collateral.',
    detailedInfo: 'A scheme for providing loans to non-corporate, non-farm small and micro enterprises for their business activities and expansion.',
    eligibility: ['Individual entrepreneur', 'Non-farm micro-business', 'Age 18+ years', 'No prior loan defaults', 'Business experience preferred but not mandatory'],
    benefits: ['Loans up to ₹10 lakh', 'No collateral required', 'Flexible repayment terms (3-5 years)', 'Government-backed security'],
    financialAssistance: 'Loans up to ₹10 lakh',
    requiredDocuments: [
      { name: 'Aadhar Card', description: 'Identity proof', optional: false },
      { name: 'Business Plan', description: '1-2 page written plan', optional: false },
      { name: 'Proof of Residence', description: 'Address proof', optional: false },
      { name: 'Photographs', description: 'Business/office photos', optional: true },
      { name: 'Bank Account Details', description: 'For loan disbursement', optional: false },
      { name: 'PAN Card', description: 'Tax identification', optional: true },
    ],
    applicationDeadline: 'Ongoing',
    applicationProcess: ['Prepare business plan', 'Apply to bank/NBFC', 'Submit documents', 'Loan processing', 'Loan approval', 'Fund disbursement'],
    targetAudience: ['Entrepreneurs', 'Self-Employed', 'Small Business Owners', 'Startups'],
    category: 'Business & Entrepreneurship',
    applicationUrl: 'https://www.mudrayojana.gov.in',
    contactPhone: '1800-180-2290',
    faq: [
      { question: 'What is the interest rate?', answer: 'Interest rates vary by bank and credit rating. Average 7-12% per annum.' },
      { question: 'Is collateral needed?', answer: 'No collateral required. It is an unsecured loan.' },
    ],
  },
  {
    id: 'scheme-007',
    name: 'Atmanirbhar Bharat Rojgar Yojana (ABRY)',
    department: 'Ministry of Labour and Employment',
    description: 'Employment incentive scheme providing contribution assistance for new workers.',
    detailedInfo: 'A special scheme to encourage employers to hire more workers during economic recovery, with government providing contribution to EPF.',
    eligibility: ['Employer registered under EPFO', 'New employee on payroll from August 2020', 'Monthly salary ≤ ₹15000', 'Employee age 18-65 years'],
    benefits: ['Employer EPF contribution (12%) for 2 years', 'Employee EPF contribution (12%) for 1 year', 'Additional government incentives'],
    financialAssistance: 'Full EPF contribution for 2 years',
    requiredDocuments: [
      { name: 'EPFO Registration', description: 'Employer registration proof', optional: false },
      { name: 'Employee Details', description: 'Name, Aadhar, salary details', optional: false },
      { name: 'Payroll Records', description: 'Salary slips and records', optional: false },
      { name: 'Bank Account', description: 'For reimbursement', optional: false },
    ],
    applicationDeadline: '30 June 2025',
    applicationProcess: ['Register with EPFO', 'Submit employee details', 'Maintain payroll records', 'EPF contribution made', 'Reimbursement after 1 year'],
    targetAudience: ['Employers', 'Manufacturing companies', 'Service providers'],
    category: 'Employment & Labor',
    applicationUrl: 'https://www.aatmanirbharbharat.gov.in',
    contactPhone: '1800-123-4567',
    faq: [
      { question: 'How much benefit does the employer get?', answer: 'Full reimbursement of 12% EPF contribution for 2 years.' },
      { question: 'Is this applicable to all sectors?', answer: 'Yes, applicable to all registered employers under EPFO.' },
    ],
  },
  {
    id: 'scheme-008',
    name: 'Beti Bachao Beti Padhao (BBBP)',
    department: 'Ministry of Women and Child Development',
    description: 'Multi-sectoral scheme to improve survival, protection, and education of girl child.',
    detailedInfo: 'A campaign to address the issue of declining child sex ratio and improve the condition of girl child in India through awareness and targeted interventions.',
    eligibility: ['Girl child (any age)', 'From any economic background', 'Indian citizens only'],
    benefits: ['Educational support', 'Healthcare facilities', 'Skill training', 'Legal protection', 'Financial support through Sukanya Samriddhi Yojana'],
    financialAssistance: '₹50000 in Sukanya Samriddhi Yojana + educational benefits',
    requiredDocuments: [
      { name: 'Birth Certificate', description: 'Girl child identification', optional: false },
      { name: 'Parent ID', description: 'Parent identification proof', optional: false },
      { name: 'Address Proof', description: 'Residence proof', optional: false },
      { name: 'Income Certificate', description: 'Family income proof', optional: true },
    ],
    applicationDeadline: 'Ongoing',
    applicationProcess: ['Register girl child', 'Complete beneficiary form', 'Submit documents', 'Enrollment in scheme', 'Receive benefits'],
    targetAudience: ['Girl Child', 'Parents', 'Guardians'],
    category: 'Women & Child Development',
    applicationUrl: 'https://www.wcd.gov.in',
    contactPhone: '1800-180-7060',
    faq: [
      { question: 'What is Sukanya Samriddhi Yojana?', answer: 'A savings scheme with 8% interest for girls, where parents can deposit up to ₹1.5 lakh annually.' },
    ],
  },
  {
    id: 'scheme-009',
    name: 'PM-WANI (Public WiFi Program)',
    department: 'Department of Telecommunications',
    description: 'Public WiFi access program to provide free internet connectivity to citizens.',
    detailedInfo: 'An initiative to provide high-speed broadband internet access through WiFi hotspots (PM-WANI) in public areas like villages, towns, and cities.',
    eligibility: ['All Indian citizens', 'No income restrictions', 'Mobile phone required'],
    benefits: ['Free WiFi access', 'High-speed internet (50+ Mbps)', 'No registration required', 'Available in public places'],
    financialAssistance: 'Free internet service',
    requiredDocuments: [
      { name: 'Mobile Phone', description: 'WiFi enabled device', optional: false },
    ],
    applicationDeadline: 'Ongoing',
    applicationProcess: ['Locate PM-WANI hotspot', 'Connect to network', 'Accept terms', 'Enjoy free internet'],
    targetAudience: ['All Citizens', 'Students', 'Job Seekers'],
    category: 'Digital Infrastructure',
    applicationUrl: 'https://dot.gov.in',
    contactPhone: '1800-123-4567',
    faq: [
      { question: 'Is PM-WANI available everywhere?', answer: 'It is expanding rapidly. Check coverage in your area on the official website.' },
    ],
  },
  {
    id: 'scheme-010',
    name: 'Pradhan Mantri Jeevan Jyoti Bima Yojana (PMJJBY)',
    department: 'Ministry of Finance',
    description: 'Term life insurance scheme for Indian citizens at affordable premium.',
    detailedInfo: 'A term life insurance scheme that provides a death benefit of ₹2 lakh to beneficiary at a very affordable premium of ₹330 per year.',
    eligibility: ['Age 18-50 years', 'Any income group', 'Indian citizen', 'Active bank account'],
    benefits: ['Death benefit: ₹2 lakh', 'Very affordable premium: ₹330/year', 'Automatic coverage if premium paid on time', 'Claims settlement within 30 days'],
    financialAssistance: '₹2 lakh life insurance coverage',
    requiredDocuments: [
      { name: 'Bank Account', description: 'For premium deduction', optional: false },
      { name: 'Aadhar Card', description: 'Identification', optional: false },
      { name: 'Age Proof', description: 'Birth certificate or ID', optional: false },
    ],
    applicationDeadline: 'Ongoing',
    applicationProcess: ['Open bank account', 'Complete application', 'Premium auto-deduction', 'Receive policy document', 'Coverage active'],
    targetAudience: ['Young Adults', 'Breadwinners', 'All Citizens'],
    category: 'Insurance & Protection',
    applicationUrl: 'https://www.pib.gov.in',
    contactPhone: '1800-425-1969',
    faq: [
      { question: 'How much is the annual premium?', answer: '₹330 per year, deducted automatically from bank account on June 1.' },
      { question: 'What if I miss a premium payment?', answer: 'Coverage gets lapsed after 3 months. You can revive it within 12 months.' },
    ],
  },
]

export const SCHEME_CATEGORIES = [
  { id: 'skill', name: 'Skill Development', icon: 'Briefcase' },
  { id: 'housing', name: 'Housing', icon: 'Home' },
  { id: 'education', name: 'Education & Scholarships', icon: 'BookOpen' },
  { id: 'finance', name: 'Financial Inclusion', icon: 'DollarSign' },
  { id: 'agriculture', name: 'Agriculture & Farming', icon: 'Sprout' },
  { id: 'business', name: 'Business & Entrepreneurship', icon: 'Zap' },
  { id: 'employment', name: 'Employment & Labor', icon: 'Users' },
  { id: 'women', name: 'Women & Child Development', icon: 'Heart' },
  { id: 'digital', name: 'Digital Infrastructure', icon: 'Wifi' },
  { id: 'insurance', name: 'Insurance & Protection', icon: 'Shield' },
]

export const TARGET_AUDIENCES = [
  'Students',
  'Farmers',
  'Women',
  'Youth',
  'Senior Citizens',
  'Entrepreneurs',
  'Low Income Families',
  'Disabled Persons',
  'Job Seekers',
]
